FORMAT: 1A
HOST: http://api-draft.kenticocloud.com/

# Kentico Draft API

![Kentico Draft](https://kenticocloud.com/logotypes/kentico_draft_rgb_small.png)

This API allows consumers to fetch content created in Kentico Draft for 
various purposes with scpecial attention to import to other systems
(CMS, ECommerce, CDN, ...) needs.

## Authorization

### API Key

### Auth0 account

## Project [/projects]

+ Attributes
    + project_id: `61e58692-47c2-4e3c` (string, required)
    + name: `The Web Project` (string, required)

### Get All Projects [GET]
+ Response 200 (application/json)
    + Attributes (array[Project])

    + Body
    
            [
                {"project_id": "61e58692-47c2-4e3c", "name": "The Web Project"}, 
                {"project_id": "3d05c3b1-c51e-4973", "name": "A Better Web"}
            ]
            
    + Schema
    
            {
              "$schema": "http://json-schema.org/draft-04/schema#",
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "project_id": {
                    "type": "string",
                    "maxLength": 40
                  },
                  "name": {
                    "type": "string",
                    "maxLength": 200
                  }
                },
                "required": [
                  "project_id",
                  "name"
                ]
              }
            }
            
### Get Projects [GET /projects/{project_id}]

+ Parameters

    + project_id: `61e58692-47c2-4e3c` (string, required)

+ Response 200 (application/json)
    + Attributes (Project)

    + Schema
    
            {
                "$schema": "http://json-schema.org/draft-04/schema#",
                "type": "object",
                "properties": {
                  "project_id": {
                    "type": "string",
                    "maxLength": 40
                  },
                  "name": {
                    "type": "string",
                    "maxLength": 200
                  }
                },
                "required": [
                  "project_id",
                  "name"
                ]
            }