FORMAT: 1A
HOST: https://api-draft.kenticocloud.com/

# Kentico Draft API

![Kentico Draft](https://kenticocloud.com/logotypes/kentico_draft_rgb_small.png)

Kentico Draft API helps you automate exporting content from Kentico Draft to the CMS of your choice. By accessing the whole content inventory, you can build your own integrations or one-off scripts to export content.

## Authorization
TODO: How to get AuthToken

### API Key

### Auth0 account

### Acces Token

## Projects [/projects]
Both content inventory and content models are always a part of a project.
+ Attributes
    + project_id: `54da688e-5489-467d-bd25-28882f4f054d` (string, required)
    + name: `Sample project` (string, required)

### Get All Projects [GET]
+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (array[Project])

    + Body
    
            [
                {"project_id": "54da688e-5489-467d-bd25-28882f4f054d", "name": "Sample project"}, 
                {"project_id": "aeea9a97-041a-4e64-be57-ede0f0be14d4", "name": "Project without delays"}
            ]

## Content Types [/projects/{project_id}/types]

+ Parameters

    + project_id: `54da688e-5489-467d-bd25-28882f4f054d` (string, required)
    
### Get all Content Types [GET]
+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (array[Content Type])
    
## Content Items [/projects/{project_id}/items{?sitemap_location,workflow_status,content_type}]

+ Parameters

    + project_id: `54da688e-5489-467d-bd25-28882f4f054d` (string, required)
    + sitemap_location: `05280be0-639a-4fc5-b3a6-7a2ea5101ab9` (string, optional) - Get only items assigned to a sitemap location. You can use this parameter more times to filter by multiple sitemap locations.
    + workflow_status: `21111b5e-6cc9-46b2-a27b-c28c5f4a0b4f` (string, optional) - Get only items with a workflow status. For example, only approved items.
    + content_type: `f82e215c-45e6-46e6-8388-c6a578291cd7` (string, optional) - Get only items for a single content type.

### Get Content Items [GET]
+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes 
        + data (array[Content Item])
        + pages - simple forward only paging
            + items_count: 128
            + pages_count: 13
            + previous: ``
            + next: `https://api-draft.kenticocloud.com/projects/54da688e-5489-467d-bd25-28882f4f054d/items?page=2`
            + first: `https://api-draft.kenticocloud.com/projects/54da688e-5489-467d-bd25-28882f4f054d/items`
            + last: `https://api-draft.kenticocloud.com/projects/54da688e-5489-467d-bd25-28882f4f054d/items?page=13`
    
## Workflow [/projects/{project_id}/workflow]

+ Parameters

    + project_id: `54da688e-5489-467d-bd25-28882f4f054d` (string, required)

### Get Workflow [GET]
+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (array[Workflow Status])
    
## Sitemap [/projects/{project_id}/sitemap]

+ Parameters

    + project_id: `54da688e-5489-467d-bd25-28882f4f054d` (string, required)

### Get Sitemap [GET]
+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes (Sitemap)
    
    + Body
    
            {
              "nodes": [
                {
                  "sitemap_node_id": "59658d3e437b8eed",
                  "name": "Home",
                },
                {
                  "sitemap_node_id": "ad66575ac0f9c35e",
                  "name": "Events",
                  "children": [
                    {
                      "sitemap_node_id": "0221017fe29c1bdb",
                      "name": "USA",
                    },
                    {
                      "sitemap_node_id": "b23cff116eba3c1b",
                      "name": "Europe",
                    }
                  ]
                },
                {
                  "sitemap_node_id": "2707dd12ab3ffd87",
                  "name": "Blog",
                }
              ]
            }
            
## Assets [/projects/{project_id}/asset/{asset_id}]

+ Parameters

    + project_id: `54da688e-5489-467d-bd25-28882f4f054d` (string, required)
    + asset_id: `287b779d-9ceb-4c8f-96c4-ea4fdb22b09d` (string, required) 

### Get Asset Download Link [GET]
Download link expires after 60 minutes.

+ Request
    + Headers

            Authorization: Bearer {access_token}

+ Response 200 (application/json)
    + Attributes
        + link: `https://horusdevelopment.blob.core.windows.net/54da688e-5489-467d-bd25-28882f4f054d/287b779d-9ceb-4c8f-96c4-ea4fdb22b09d/blogpost_teaser.jpg?sv=2015-02-21&sig=FVArbWI7zCodmEMJ69DE4JCiyfhqj` (string, required) - Temporary asset download link.
        + exp: `2016-06-11T12:55:28.29493Z` (string, required) - Asset download link expiration date and time in ISO 8601 format.

##########################################################

# Data Structures

## Content Type (object)
+ `type_id`: 8e879b999dd26639 (string, required)
+ name: Blog (string, required) - Max 50 characters
+ elements (array)
    - (StringTypeElement)
    - (RichTextTypeElement)
    - (NumberTypeElement)
    - (DateTimeTypeElement)
    - (AssetTypeElement)
    - (ModularContentTypeElement)

## TypeElementBase (object)
+ `type_element_id` (string, required)
+ name (string, required)
+ type (enum, required)
    - string
    - number
    - rich_text
    - assets
    - modular_content
    - date_time
+ guidelines (string)

## AssetTypeElement (TypeElementBase)
+ `type_element_id`: 9abb70a524a65e00
+ name: Teaser image
+ type: assets
+ guidelines: `Attach teaser image, max. dimensions are 1024 × 400 px, allowed formats are *.jpg, *.png, *.gif.`

## DateTimeTypeElement (TypeElementBase)
+ `type_element_id`: bef3ad230736ead1
+ name: Publication date
+ type: date_time
+ guidelines: `Provide the date that should appear on a live site as the date this article was posted live. Furthermore, this date will influence the order of the articles in the list of articles.`

## NumberTypeElement (TypeElementBase)
+ `type_element_id`: bcc618ae3faf21eb
+ name: Price in USD
+ type: number
+ guidelines: `Article price. 0 means this artcile is free.`

## StringTypeElement (TypeElementBase)
+ `type_element_id`: a0b10a4d16fa9186
+ name: Title
+ type: string
+ guidelines: `Provide a title that will fit within 60 characters.`

## RichTextTypeElement (StringTypeElement)
+ `type_element_id`: bfc7bf641ad5350c
+ name: Body
+ type: rich_text
+ guidelines: `Keep the blog post structured with concise paragraphs complemented with headlines that will help the reader navigate through the article's content.`

## ModularContentTypeElement (TypeElementBase)
+ `type_element_id`: bc6ff87ec6aa95f0
+ name: Features
+ type: modular_content
+ guidelines: `Assign at most 3 Features that have been prepared for a home page.`

############################################

## Content Item (object)
+ `item_id`: 8d2c787c7b08ad9c (string, required)
+ name: Blog post (string, required) - Max 50 characters
+ sitemam_location (array[string])
    - 821fe4ebbbbf7cd2
    - a8fec4b5039816d9
+ last_modified: 2016-06-09T14:41:10.6814919Z (string, required)
+ workflow_status (Workflow Status, required)
+ elements (array)
    - (StringItemElement)
    - (RichTextItemElement)
    - (NumberItemElement)
    - (DateTimeItemElement)
    - (AssetItemElement)
    - (ModularContentItemElement)

## Workflow Status (object)
+ workflow_id: 9ad09d2e5f7532ae
+ name: Draft (string, required)
+ color: red (enum, required)
    - red
    - pink
    - purple
    - `deep-purple`
    - indigo
    - blue
    - cyan
    - teal
    - green
    - `light-green`
    - lime
    - yellow
    - amber
    - orange
    - brown
    - grey
    - `light-grey`

## ItemElementBase (object)
+ `item_id` (string, required)
+ name (string, required)
+ type (enum, required)
    - string
    - number
    - rich_text
    - assets
    - modular_content
    - date_time
    
## Asset (object)
+ asset_id: 924ea5f1e4c68ed8 (string, required)
+ name: blogpost_teaser.jpg (string, required) - file name
+ type: image/jpg (string, required) - file mime type
+ size: 135897 (number, required) - size of file (unsigned integer)
+ last_modified: 2016-03-31T08:04:14.7525987Z (string, required) - time of asset upload

## AssetItemElement (ItemElementBase)
+ `item_id`: e9abb70a524a65e00
+ type: asset
+ name: Teaser image
+ value (array[Asset], required) - list of assets

## DateTimeItemElement (ItemElementBase)
+ `item_id`: cbef3ad230736ead1
+ name: Publication date
+ type: date_time (string, optional) - ISO 8601 date time
+ value: 2016-03-19T00:00:00Z

## NumberItemElement (ItemElementBase)
+ `item_id`: abcc618ae3faf21eb
+ name: Price in USD
+ value: 49.9 (number, optional)

## StringItemElement (ItemElementBase)
+ `item_id`: ba0b10a4d16fa9186
+ name: Title
+ value: Sample blog post (string, optional)

## RichTextItemElement (StringItemElement)
+ `item_id`: 8bfc7bf641ad5350c
+ name: Body
+ type: rich_text
+ value: `<p>There are many different types of blogs, differing not only in the type of content, but also in the way that content is delivered or written.&nbsp;</p>\n<h2>Personal blogs</h2>` (string, optional)

## Content Item Reference (object)
+ `item_id`: 8d2c787c7b08ad9c (string, required)
+ name: Blog post (string, required)

## ModularContentItemElement (ItemElementBase)
+ `item_id`: fbc6ff87ec6aa95f0
+ name: Features
+ type: modular_content
+ value (array[Content Item Reference], required)

############################################

## Sitemap Node (object)
+ `sitemap_node_id`: 897f-8e395386de7a (string, required)
+ name: Home (string, required)
+ children (array[Sitemap Node])

## Sitemap (object)
+ nodes (array[Sitemap Node])